### ISSUE TITLE
Bigger test dataset

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/modflow2netcdf#1]
I spoke with @langevin-usgs today and he mentioned a much larger dataset for testing.    @kwilcox, did you get that going?

**Comment by kwilcox** [comment]
@rsignell-usgs @langevin-usgs I am testing with the Colorado River Basin results.  If there is anything larger than that I should test with let me know!

**Comment by langevin-usgs** [comment]
Kyle, I had sent a Miami-Dade model a while back (or i posted it somewhere).  I think that would be another good one to test.
