### ISSUE TITLE
Couple small things with "heads" variable

### ISSUE THREAD

**Issue by langevin-usgs** [axiom-data-science/modflow2netcdf#7]
Kyle, couple small things:

1.  I know this is trivial, but can you change the variable name "heads" to "head".  This is what it is called in the MODFLOW binary heads file and elsewhere.

2.  The units for head are incorrect.  They should be length units, not length units ^3 / time.

**Comment by kwilcox** [comment]
Fixed in https://github.com/axiom-data-science/modflow2netcdf/commit/5e788d8467fd1fcebd7ac377ec636fefaf6f8190
