### ISSUE TITLE
Required versions for numpy and matplotlib

### ISSUE THREAD

**Issue by ocefpaf** [axiom-data-science/modflow2netcdf#9]
@kwilcox the `requirements.txt` says:

```
numpy<1.9
matplotlib<1.4
```

are those still true? They are blocking me from creating modern conda recipe \* for this module.

\* One that plays nice with other modules installed :wink:

**Comment by langevin-usgs** [comment]
@ocefpaf we have been working on a fork that will ultimately replace this one.  It is at: https://github.com/spaulins-usgs/modflow2netcdf.  We have removed those requirements there.

**Comment by ocefpaf** [comment]
Thanks for the info. As your group is probably the most important users of this module would you (or someone from your group) be willing to:

- make a new release with those changes (either here or in the fork);
- be the maintainer of the recipe at the community channel conda-forge \*.

I am available to answer any question you might have about conda-forge, but here is the gist of it:
conda-forge's goal is to get the developers and/or power users involved in the creation of the conda recipe for the packages they judge important to them. You would have commit rights to the repository where the recipe lives and, after each version/recipe update, a new binary is uploaded to the conda-forge channel.

\* See https://github.com/conda-forge/staged-recipes/pull/166 for the recipe.
